"""update trusted permissions

Revision ID: 1f77e27629bd
Revises: 4bd16c0543ba
Create Date: 2015-02-15 11:52:59.017593

"""

# revision identifiers, used by Alembic.
revision = '1f77e27629bd'
down_revision = '4bd16c0543ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_perms', sa.Column('permissions', sa.UnicodeText(), nullable=False))
    op.drop_column('trusted_perms', 'permission')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_perms', sa.Column('permission', sa.TEXT(), nullable=False))
    op.drop_column('trusted_perms', 'permissions')
    ### end Alembic commands ###
