"""Add certificate to groups

Revision ID: 386b6227f0b
Revises: 400129ba655f
Create Date: 2015-01-10 03:01:47.856746

"""

# revision identifiers, used by Alembic.
revision = '386b6227f0b'
down_revision = '400129ba655f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('certificate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'certificates', ['certificate'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'certificate')
    ### end Alembic commands ###
