"""Clean up obsolete 2014

Revision ID: 400129ba655f
Revises:
Create Date: 2015-02-08 23:00:39.661042

"""

# revision identifiers, used by Alembic.
revision = '400129ba655f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_status')
    op.drop_table('role_level')
    op.drop_table('membership_request')
    op.alter_column('group_membership', 'sponsor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'group_membership', type_='foreignkey')
    op.alter_column('people', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.alter_column('signed_license_agreement', 'license',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('signed_license_agreement', 'people',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signed_license_agreement', 'people',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('signed_license_agreement', 'license',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'people', 'account_status', ['status'], ['id'])
    op.alter_column('people', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'group_membership', 'role_level', ['role'], ['id'])
    op.create_foreign_key(None, 'group_membership', 'account_status', ['status'], ['id'])
    op.alter_column('group_membership', 'sponsor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_table('membership_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('person_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
