"""Add Certificates Management

Revision ID: 400129ba655f
Revises: 
Create Date: 2015-01-08 23:30:47.791401

"""

# revision identifiers, used by Alembic.
revision = '400129ba655f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('cert', sa.UnicodeText(), nullable=False),
    sa.Column('cert_key', sa.UnicodeText(), nullable=False),
    sa.Column('client_cert_desc', sa.UnicodeText(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('certificates_idx', 'certificates', ['id'], unique=False)
    op.create_table('clients_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('certificate', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['ca'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['people'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_certificates')
    op.drop_index('certificates_idx', table_name='certificates')
    op.drop_table('certificates')
    ### end Alembic commands ###
