"""Add ssh requirement option to group

Revision ID: 42b18c3a031b
Revises: 56a14c3a012c
Create Date: 2015-09-06 10:48:47.226136

"""

# revision identifiers, used by Alembic.
revision = '42b18c3a031b'
down_revision = '56a14c3a012c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('requires_ssh', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'requires_ssh')
    ### end Alembic commands ###
