"""Add trusted permissions

Revision ID: 4bd16c0543ba
Revises: 15b28d3a0911
Create Date: 2015-02-08 23:56:55.863764

"""

# revision identifiers, used by Alembic.
revision = '4bd16c0543ba'
down_revision = '15b28d3a0911'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_perms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application', sa.UnicodeText(), nullable=False),
    sa.Column('token', sa.UnicodeText(), nullable=False),
    sa.Column('secret', sa.UnicodeText(), nullable=False),
    sa.Column('permissions', sa.UnicodeText(), nullable=False),
    sa.Column('granted_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trusted_perms')
    ### end Alembic commands ###
