"""Update column naming for consistency

Revision ID: c3f6e45190ca
Revises: 478ba3409f2a
Create Date: 2016-06-12 21:04:13.418114

"""

# revision identifiers, used by Alembic.
revision = 'c3f6e45190ca'
down_revision = '478ba3409f2a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('certificate', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['ca'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clients_certificates')
    op.add_column('account_permissions', sa.Column('person_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'account_permissions_people_fkey', 'account_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'account_permissions', 'people', ['person_id'], ['id'])
    op.drop_column('account_permissions', 'people')
    op.add_column('group_membership', sa.Column('sponsor_id', sa.Integer(), nullable=True))
    op.add_column('group_membership', sa.Column('update_timestamp', sa.DateTime(), nullable=True))
    op.drop_constraint(u'group_membership_sponsor_fkey', 'group_membership', type_='foreignkey')
    op.create_foreign_key(None, 'group_membership', 'people', ['sponsor_id'], ['id'])
    op.drop_column('group_membership', 'sponsor')
    op.drop_column('group_membership', 'approval_timestamp')
    op.add_column('groups', sa.Column('certificate_id', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('update_timestamp', sa.DateTime(), nullable=False))
    op.drop_constraint(u'groups_certificate_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'certificates', ['certificate_id'], ['id'])
    op.drop_column('groups', 'updated_timestamp')
    op.drop_column('groups', 'certificate')
    op.add_column('people_activity_log', sa.Column('event_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('people_activity_log', 'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_activity_log', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('people_activity_log', 'event_timestamp')
    op.add_column('groups', sa.Column('certificate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('updated_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(u'groups_certificate_fkey', 'groups', 'certificates', ['certificate'], ['id'])
    op.drop_column('groups', 'update_timestamp')
    op.drop_column('groups', 'certificate_id')
    op.add_column('group_membership', sa.Column('approval_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('group_membership', sa.Column('sponsor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_membership', type_='foreignkey')
    op.create_foreign_key(u'group_membership_sponsor_fkey', 'group_membership', 'people', ['sponsor'], ['id'])
    op.drop_column('group_membership', 'update_timestamp')
    op.drop_column('group_membership', 'sponsor_id')
    op.add_column('account_permissions', sa.Column('people', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'account_permissions', type_='foreignkey')
    op.create_foreign_key(u'account_permissions_people_fkey', 'account_permissions', 'people', ['people'], ['id'])
    op.drop_column('account_permissions', 'person_id')
    op.create_table('clients_certificates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ca', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('serial', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ca'], [u'certificates.id'], name=u'clients_certificates_ca_fkey'),
    sa.ForeignKeyConstraint(['people'], [u'people.id'], name=u'clients_certificates_people_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'clients_certificates_pkey')
    )
    op.drop_table('people_certificates')
    ### end Alembic commands ###
